### ISSUE TITLE
Некоректна перевірка пов'язаності країн

### ISSUE THREAD

**Issue by KirillRedin** [Ghost207/EuroDif#3]
Через некоректний рекурсивний виклик для перевірки, чи всі країни пов'язані між собою, деякі правильні кейси виконуються з помилкою.
https://github.com/Ghost207/EuroDif/blob/954e56c2c696da68dafafb2669fe1a7adc442602/main.cpp#L305

**Comment by Ghost207** [comment]
Fixed
https://github.com/Ghost207/EuroDif/commit/d62175ea49a77ead942cf486d983f8b5110d71be
