### ISSUE TITLE
Проблема при утворенні пар

### ISSUE THREAD

**Issue by KirillRedin** [Ghost207/EuroDif#4]
В деяких випадках через невірне формування пар країн програма входить в нескінченний цикл.
https://github.com/Ghost207/EuroDif/blob/954e56c2c696da68dafafb2669fe1a7adc442602/main.cpp#L354

**Comment by Ghost207** [comment]
https://github.com/Ghost207/EuroDif/commit/9066f4759f6c2ad16b352d046f015dc08f1dfe36
